/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import { CarCard } from "./CarCard";
import { Button } from "../builderio";

interface CarCatalogProps {}

export const CarCatalog: React.FC<CarCatalogProps> = () => {
  const popularCars = [
    {
      name: "Koenigsegg",
      type: "Sport",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ad94ba3fa768cf08efac7dd87527b49a044d03df1aaddbfebab475740a0990ac?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11",
      price: 99.0,
      fuel: "90L",
      transmission: "Manual",
      capacity: "2 People",
    },
    {
      name: "Nissan GT - R",
      type: "Sport",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/0fcb91e0a3e0d631e1a00a1f40e7a653282e71246a4f53003a2c5b9a6cfa4662?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11",
      price: 80.0,
      fuel: "80L",
      transmission: "Manual",
      capacity: "2 People",
      oldPrice: 100.0,
    },
    {
      name: "Rolls - Royce",
      type: "Sedan",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/7df1797b8ccbf404cd965aafd8c16a08801bd57509055765288adfab46235579?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11",
      price: 96.0,
      fuel: "70L",
      transmission: "Manual",
      capacity: "4 People",
    },
    {
      name: "Nissan GT - R",
      type: "Sport",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/3530ed554a5a174ab5700b32add508605f5a4816ecdc6f73fa28bd8b463cfbe6?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11",
      price: 80.0,
      fuel: "80L",
      transmission: "Manual",
      capacity: "2 People",
      oldPrice: 100.0,
    },
  ];

  const recommendedCars = [
    {
      name: "All New Rush",
      type: "SUV",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f7eeca3e93d082a6ef6dc526dd3054a4bdd7eee7f37aaceca11e5a9f17de5740?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11",
      price: 72.0,
      fuel: "70L",
      transmission: "Manual",
      capacity: "6 People",
      oldPrice: 80.0,
    },
    {
      name: "CR - V",
      type: "SUV",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/92eff38d0131f14af090eb3445b7c88a283b79b088904e97b70cef684856a3e0?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11",
      price: 80.0,
      fuel: "80L",
      transmission: "Manual",
      capacity: "6 People",
    },
    {
      name: "All New Terios",
      type: "SUV",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/de07b5d3db71f34ddea26cfb8ff7efe9e0a7f9124a6bc8019523f92e7b060b49?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11",
      price: 74.0,
      fuel: "90L",
      transmission: "Manual",
      capacity: "6 People",
    },
    {
      name: "CR - V",
      type: "SUV",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/1d687c8f2139426ae450a88b4cf96fd5791015be7636bb99b73b6d11cbd658ca?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11",
      price: 80.0,
      fuel: "80L",
      transmission: "Manual",
      capacity: "6 People",
    },
    {
      name: "MG ZX Exclusice",
      type: "Hatchback",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/5102b26a6029d3c93459c6a8627b5b6e46d4d0d39d03d26d28a26d323565a111?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11",
      price: 76.0,
      fuel: "70L",
      transmission: "Manual",
      capacity: "4 People",
      oldPrice: 80.0,
    },
    {
      name: "New MG ZS",
      type: "SUV",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/546d63ade72379f9a276b1ca855b68e1986cfd8f24424ed0f5f38bc286c9e45a?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11",
      price: 80.0,
      fuel: "80L",
      transmission: "Manual",
      capacity: "6 People",
    },
    {
      name: "MG ZX Excite",
      type: "Hatchback",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/5102b26a6029d3c93459c6a8627b5b6e46d4d0d39d03d26d28a26d323565a111?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11",
      price: 74.0,
      fuel: "90L",
      transmission: "Manual",
      capacity: "4 People",
    },
    {
      name: "New MG ZS",
      type: "SUV",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/2e58d84807ece87dc212743b47f0969ec93b1c7af9273a6d3c3ab9bbd86a1756?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11",
      price: 80.0,
      fuel: "80L",
      transmission: "Manual",
      capacity: "6 People",
    },
  ];

  return (
    <StyledCarCatalog>
      <Section>
        <SectionHeader>
          <h2>Popular Car</h2>
          <ViewAll>View All</ViewAll>
        </SectionHeader>
        <CarGrid>
          {popularCars.map((car, index) => (
            <CarCard key={index} {...car} />
          ))}
        </CarGrid>
      </Section>
      <Section>
        <SectionHeader>
          <h2>Recommended Car</h2>
        </SectionHeader>
        <CarGrid>
          {recommendedCars.map((car, index) => (
            <CarCard key={index} {...car} />
          ))}
        </CarGrid>
      </Section>
      <ShowMore>
        <Button variant="contained">Show more cars</Button>
        <span>120 Car</span>
      </ShowMore>
    </StyledCarCatalog>
  );
};

const StyledCarCatalog = styled.section`
  margin-top: 32px;
`;

const Section = styled.div`
  margin-bottom: 32px;
`;

const SectionHeader = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
`;

const ViewAll = styled.a`
  color: var(--Primary-500);
  cursor: pointer;
`;

const CarGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 32px;
`;

const ShowMore = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 16px;
  margin-top: 64px;
`;
