/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import { LikeButton } from "../builderio";
import { LocalGasStation, People } from "../builderio";
import { Button } from "../builderio";

interface CarCardProps {
  name: string;
  type: string;
  image: string;
  price: number;
  fuel: string;
  transmission: string;
  capacity: string;
  oldPrice?: number;
}

export const CarCard: React.FC<CarCardProps> = ({
  name,
  type,
  image,
  price,
  fuel,
  transmission,
  capacity,
  oldPrice,
}) => {
  return (
    <StyledCarCard>
      <CardHeader>
        <CarInfo>
          <CarName>{name}</CarName>
          <CarType>{type}</CarType>
        </CarInfo>
        <LikeButton />
      </CardHeader>
      <CarImage src={image} alt={name} />
      <Specifications>
        <Spec>
          <LocalGasStation />
          <span>{fuel}</span>
        </Spec>
        <Spec>
          <TransmissionIcon
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/563fd9367e8be9e271233fa362e88c8b2205c920475aad51a787f2599d87477e?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11"
            alt="Transmission"
          />
          <span>{transmission}</span>
        </Spec>
        <Spec>
          <People />
          <span>{capacity}</span>
        </Spec>
      </Specifications>
      <CardFooter>
        <PriceInfo>
          <Price>
            ${price.toFixed(2)}/ <span>day</span>
          </Price>
          {oldPrice && <OldPrice>${oldPrice.toFixed(2)}</OldPrice>}
        </PriceInfo>
        <Button variant="contained">Rent Now</Button>
      </CardFooter>
    </StyledCarCard>
  );
};

const StyledCarCard = styled.article`
  background-color: var(--Primary-0);
  border-radius: 10px;
  padding: 24px;
  display: flex;
  flex-direction: column;
`;

const CardHeader = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
`;

const CarInfo = styled.div`
  display: flex;
  flex-direction: column;
`;

const CarName = styled.h3`
  color: var(--Secondary-500);
  margin: 0;
`;

const CarType = styled.span`
  color: var(--Secondary-300);
`;

const CarImage = styled.img`
  width: 100%;
  height: auto;
  margin: 24px 0;
`;

const Specifications = styled.div`
  display: flex;
  justify-content: space-between;
  margin-bottom: 24px;
`;

const Spec = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
  color: var(--Secondary-300);
`;

const TransmissionIcon = styled.img`
  width: 24px;
  height: 24px;
`;

const CardFooter = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
`;

const PriceInfo = styled.div`
  display: flex;
  flex-direction: column;
`;
const Price = styled.span`
  color: var(--Secondary-300);
  font-weight: bold;

  span {
    font-size: 14px;
    color: rgba(144, 163, 191, 1);
  }
`;

const OldPrice = styled.span`
  color: var(--Secondary-300);
  text-decoration: line-through;
  font-size: 14px;
`;
