/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styled from 'styled-components';
import { NavBar } from './NavBar';
import { SearchSection } from './SearchSection';
import { CarCatalog } from './CarCatalog';
import { Footer } from './Footer';

interface CarRentalProps {}

export const CarRental: React.FC<CarRentalProps> = () => {
  return (
    <StyledCarRental>
      <NavBar />
      <main>
        <SearchSection />
        <CarCatalog />
      </main>
      <Footer />
    </StyledCarRental>
  );
};

const StyledCarRental = styled.div`
  background-color: #fff;
  display: flex;
  flex-direction: column;
  overflow: hidden;
`;