/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styled from 'styled-components';

interface FooterProps {}

export const Footer: React.FC<FooterProps> = () => {
  return (
    <StyledFooter>
      <TopGroup>
        <LogoSection>
          <Logo>MORENT</Logo>
          <Vision>Our vision is to provide convenience and help increase your sales business.</Vision>
        </LogoSection>
        <LinksSection>
          <LinkColumn>
            <h4>About</h4>
            <ul>
              <li>How it works</li>
              <li>Featured</li>
              <li>Partnership</li>
              <li>Business Relation</li>
            </ul>
          </LinkColumn>
          <LinkColumn>
            <h4>Community</h4>
            <ul>
              <li>Events</li>
              <li>Blog</li>
              <li>Podcast</li>
              <li>Invite a friend</li>
            </ul>
          </LinkColumn>
          <LinkColumn>
            <h4>Socials</h4>
            <ul>
              <li>Discord</li>
              <li>Instagram</li>
              <li>Twitter</li>
              <li>Facebook</li>
            </ul>
          </LinkColumn>
        </LinksSection>
      </TopGroup>
      <Divider />
      <BottomGroup>
        <Copyright>©2022 MORENT. All rights reserved</Copyright>
        <LegalLinks>
          <a href="#">Privacy & Policy</a>
          <a href="#">Terms & Condition</a>
        </LegalLinks>
      </BottomGroup>
    </StyledFooter>
  );
};

const StyledFooter = styled.footer`
  background-color: var(--Primary-0);
  padding: 70px 60px;
  @media (max-width: 991px) {
    padding: 40px 20px;
  }
`;

const TopGroup = styled.div`
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 40px;
`;

const LogoSection = styled.div`
  max-width: 292px;
`;

const Logo = styled.h2`
  color: var(--Primary-500);
  margin: 0 0 16px;
`;

const Vision = styled.p`
  margin: 0;
`;

const LinksSection = styled.div`
  display: flex;
  gap: 60px;
  @media (max-width: 768px) {
    flex-direction: column;
    gap: 30px;
  }
`;

const LinkColumn = styled.div`
  h4 {
    color: var(--Secondary-500);
    margin: 0 0 16px;
  }

  ul {
    list-style-type: none;
    padding: 0;
    margin: 0;

    li {
      margin-bottom: 12px;
    }
  }
`;

const Divider = styled.hr`
  border: none;
  border-top: 1px solid rgba(19, 19, 19, 0.16);
  margin: 36px 0;
`;

const BottomGroup = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
  gap: 20px;
`;

const Copyright = styled.p`
  color: var(--Secondary-500);
  margin: 0;
`;

const LegalLinks = styled.div`
  display: flex;
  gap: 40px;

  a {
    color: var(--Secondary-500);
    text-decoration: none;
  }
`;