/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import {
  LikeButton,
  NotificationButton,
  SettingsButton,
  SearchButton,
  TuneButton,
} from "../builderio";
import { TextField } from "../builderio";

interface NavBarProps {}

export const NavBar: React.FC<NavBarProps> = () => {
  return (
    <StyledNavBar>
      <LeftSection>
        <Logo>MORENT</Logo>
        <SearchBar>
          <SearchButton />
          <StyledTextField variant="standard" placeholder="Search" />
          <TuneButton />
        </SearchBar>
      </LeftSection>
      <ProfileSection>
        <LikeButton />
        <NotificationButton />
        <SettingsButton />
        <ProfileImage
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/35d11352db6804c69bba6d5409f945bc4ea04bd28a16cf87b77b013c72f898fa?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11"
          alt="Profile"
        />
      </ProfileSection>
    </StyledNavBar>
  );
};

const StyledNavBar = styled.nav`
  justify-content: space-between;
  align-items: center;
  background-color: var(--Primary-0);
  display: flex;
  width: 100%;
  padding: 40px 32px;
  @media (max-width: 991px) {
    padding: 20px;
  }
`;

const LeftSection = styled.div`
  display: flex;
  align-items: center;
  gap: 82px;
  @media (max-width: 991px) {
    flex-wrap: wrap;
    gap: 20px;
  }
`;

const Logo = styled.h1`
  color: var(--Primary-500);
  margin: 0;
`;

const SearchBar = styled.div`
  display: flex;
  align-items: center;
  gap: 20px;
  border: 1px solid rgba(195, 212, 233, 0.4);
  border-radius: 70px;
  padding: 10px 20px;
  background-color: var(--Primary-0);
`;

const StyledTextField = styled(TextField)`
  flex-grow: 1;
`;

const ProfileSection = styled.div`
  display: flex;
  align-items: center;
  gap: 20px;
`;

const ProfileImage = styled.img`
  width: 44px;
  height: 44px;
  border-radius: 50%;
  object-fit: cover;
`;
