/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import { Radio } from "../builderio";
import { Select } from "../builderio";

interface SearchSectionProps {}

export const SearchSection: React.FC<SearchSectionProps> = () => {
  return (
    <StyledSearchSection>
      <SearchCard>
        <RadioGroup>
          <Radio color="default" size="medium" />
          <span>Pick - Up</span>
        </RadioGroup>
        <SearchFields>
          <Field>
            <Label>Locations</Label>
            <Select variant="standard" placeholder="Select your city" />
          </Field>
          <Divider />
          <Field>
            <Label>Date</Label>
            <Select variant="standard" placeholder="Select your date" />
          </Field>
          <Divider />
          <Field>
            <Label>Time</Label>
            <Select variant="standard" placeholder="Select your time" />
          </Field>
        </SearchFields>
      </SearchCard>
      <SwapIcon
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/7f753351d3e874081da5f2df3bec7d762224e40229cd863c959883cf004e5b82?placeholderIfAbsent=true&apiKey=6434028ab27e480a9780a25873a33e11"
        alt="Swap"
      />
      <SearchCard>
        <RadioGroup>
          <Radio color="default" size="medium" />
          <span>Drop - Off</span>
        </RadioGroup>
        <SearchFields>
          <Field>
            <Label>Locations</Label>
            <Select variant="standard" placeholder="Select your city" />
          </Field>
          <Divider />
          <Field>
            <Label>Date</Label>
            <Select variant="standard" placeholder="Select your date" />
          </Field>
          <Divider />
          <Field>
            <Label>Time</Label>
            <Select variant="standard" placeholder="Select your time" />
          </Field>
        </SearchFields>
      </SearchCard>
    </StyledSearchSection>
  );
};

const StyledSearchSection = styled.section`
  display: flex;
  justify-content: space-between;
  margin-top: 32px;
  gap: 20px;
  @media (max-width: 991px) {
    flex-direction: column;
  }
`;

const SearchCard = styled.div`
  background-color: var(--Primary-0);
  border-radius: 10px;
  padding: 24px;
  flex: 1;
`;

const RadioGroup = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
`;

const SearchFields = styled.div`
  display: flex;
  margin-top: 16px;
  gap: 24px;
  @media (max-width: 991px) {
    flex-direction: column;
  }
`;

const Field = styled.div`
  display: flex;
  flex-direction: column;
  flex: 1;
`;

const Label = styled.label`
  color: var(--Secondary-500);
  margin-bottom: 8px;
`;

const Divider = styled.div`
  width: 1px;
  background-color: rgba(195, 212, 233, 0.4);
  @media (max-width: 991px) {
    display: none;
  }
`;

const SwapIcon = styled.img`
  width: 60px;
  height: 60px;
  align-self: center;
`;
